[profile.default]
src = "packages/contracts/src"
test = "packages/contracts/test"
out = "packages/contracts/out"
cache_path = "packages/contracts/cache"
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 20_000
ffi = false

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
